### PR TITLE
allow outside code to tell the widget the refreshing is on

### PR DESCRIPTION
**Pull request by robUx4**
In Plume we also do a refresh with an outside better and we want the list to tell that is being refreshed as if it was done manually

### CODE REVIEW

**Comment by chrisbanes** [comment]
Why is the boolean parameter needed for `setRefreshing()`? If you do not want the UI to scroll/change then simply don't called the method.

**Comment by robUx4** [comment]
I need to tell the widget the refreshing is being done, so that visually the user know about it and doesn't refresh while it's already being done. But I don't want to it scroll to the pull header/footer as it may not be displayed at all at that time.

**Comment by chrisbanes** [comment]
OK, but if you don't scroll then the widget will never display the loading view (the scrolling is for the `LinearLayout`, **not** the `ListView`, etc).

If you don't want the Loading View to show, don't call `setRefreshing()`

**Comment by robUx4** [comment]
I think we don't understand each other.
In Plume when I push the refresh button it may take a while. During that time I want the widget to say the refresh is in progress, as if it had been pulled manually. But I don't want the LinearLayout to show while it's doing so. I want it to say it's refreshing only when it's being pulled.

**Comment by chrisbanes** [comment]
Oh I understand now. So you want the widget to widget to say the refresh is in progress if the user pulls?

**Comment by robUx4** [comment]
Correct

**Comment by chrisbanes** [comment]
OK that definitely makes sense now. Thanks.

**Comment by jhon-chavarria** [comment]
hi, i have a question , can any body help me?

**Pull request merged**
