### PR TITLE
Exposed internal API's for subclassing

### PR DESCRIPTION
**Pull request by DHuckaby**
I found I needed to expose these API's during development, it may help future customization efforts.

### CODE REVIEW

**Comment by chrisbanes** [comment]
I've tweaked your pull for dev. Thanks!

**Comment by DHuckaby** [comment]
I just now got around to switching back to your repo. In your merge you lost my getter for the animation duration.

**Comment by mikepenz** [comment]
I did a rebase to your repo again. So my repo should include all your changes again. Thanks.

**Comment by chrisbanes** [comment]
@DHuckaby: My implementation is slightly different to yours. The duration can be set each time when calling `smoothScrollTo()`, there is also a default duration which can be found by `PullToRefreshBase.SMOOTH_SCROLL_DURATION_MS`

**Comment by DHuckaby** [comment]
@chrisbanes Because smoothScrollTo() is final I cannot insert my own duration, and because you call the non-overloaded method internally their is no way for me to actually change anything.

**Comment by chrisbanes** [comment]
@DHuckaby: Good point. I'll change it in dev now.

_EDIT: Fixed in 74b6914ff2b112ac8e1ae3465f6729a054321e18_

**Pull request closed without merging**
