### PR TITLE
Fix setRefreshing

### PR DESCRIPTION
**Pull request by hank-cp**
Fix setRefreshing for PullToRefreshExpandableListView. Show LoadingLayout if EmptyView is not set

### CODE REVIEW

**Comment by DHuckaby** [comment]
Try not to format the files you change, it basically obfuscates the commit.

**Comment by hank-cp** [comment]
Should be the plugin that converts tab-to-space automatically. Thanks your notice, I will shut it down next time.

**Comment by terryyhl** [comment]
when i use two tabhost 

03-20 20:16:00.575: E/AndroidRuntime(30565): FATAL EXCEPTION: main
03-20 20:16:00.575: E/AndroidRuntime(30565): java.lang.StackOverflowError
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.graphics.Canvas.drawText(Canvas.java:1310)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.text.Layout.draw(Layout.java:437)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.widget.TextView.onDraw(TextView.java:4305)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.View.draw(View.java:6933)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.widget.AbsListView.dispatchDraw(AbsListView.java:1648)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.widget.ListView.dispatchDraw(ListView.java:3172)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at com.ylmf.androidclient.view.PullToRefreshListView$InternalListView.dispatchDraw(PullToRefreshListView.java:334)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.View.draw(View.java:6936)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.widget.AbsListView.draw(AbsListView.java:3030)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.View.draw(View.java:6936)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.View.draw(View.java:6936)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.widget.FrameLayout.draw(FrameLayout.java:357)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.View.draw(View.java:6936)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.widget.FrameLayout.draw(FrameLayout.java:357)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.View.draw(View.java:6936)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.widget.FrameLayout.draw(FrameLayout.java:357)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.View.draw(View.java:6936)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.widget.FrameLayout.draw(FrameLayout.java:357)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at com.slidingmenu.lib.CustomViewAbove.dispatchDraw(CustomViewAbove.java:842)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.View.draw(View.java:6936)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.View.draw(View.java:6936)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.widget.FrameLayout.draw(FrameLayout.java:357)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1908)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewRoot.draw(ViewRoot.java:1529)
03-20 20:16:00.575: E/AndroidRuntime(30565):    at android.view.ViewRoot.performTrav

**Comment by Yougin** [comment]
I've got the same issue as Terry do. I've contacted Terry and he advice to use merge or viewstub which works perfectly fine for me.

**Comment by chrisbanes** [comment]
This project is deprecated.

**Pull request closed without merging**
