### PR TITLE
PullToRefreshListView additional header/footer views

### PR DESCRIPTION
**Pull request by roosmaa**
This fixes the issue #79 I reported earlier.

Currently pull-to-refresh stops working when the ListView is empty and there are additional header/footer views added to it. This changes the number of internal header/footer views to return the actual number from the underlying ListView itself.

### CODE REVIEW

**Comment by chrisbanes** [comment]
Thanks, but this isn't quite the right way to fix it.

**Comment by pchauhan** [comment]
Hello I need some help related Header Footer Image.
I want to set header footer image at runtime .i have set like

subCategoryListView .setOnRefreshListener(new OnRefreshListener2<ListView>() {
        public void onPullDownToRefresh(PullToRefreshBase<ListView> refreshView) {
            ImageView   mHeaderImage = (ImageView) refreshView.findViewById(R.id.pull_to_refresh_image);
            mHeaderImage.setBackgroundResource(R.drawable.ic_launcher);
            subCategoryListView.onRefreshComplete();
        }
        public void onPullUpToRefresh(PullToRefreshBase<ListView> refreshView) {
            ImageView   mHeaderImage = (ImageView)refreshView.findViewById(R.id.pull_to_refresh_image);
         setBackgroundResource(R.drawable.action_arrow_down);
           subCategoryListView.onRefreshComplete();
        }
    });
But problem is everytime image set at header and leave some space when refreshComplete.

Plz suggest me
Thanks 
Parag

**Comment by chrisbanes** [comment]
@pchauhan You should have opened another issue for this. Anyway you shouldn't be changing the image like that, use `setLoadingDrawable(...)` instead.

**Comment by pchauhan** [comment]
pls suggest me how to set header and footer different images
i have set like this but still not get 

mPullRefreshListView.setOnRefreshListener(new OnRefreshListener2() {

```
        @Override
        public void onPullDownToRefresh(PullToRefreshBase refreshView) {
            // TODO Auto-generated method stub


            Drawable d = getResources().getDrawable(R.drawable.icon);
            refreshView.setLoadingDrawable(d);
mPullRefreshListView.onRefreshComplete();
        }

        @Override
        public void onPullUpToRefresh(PullToRefreshBase refreshView) {
            // TODO Auto-generated method stub


            Drawable d = getResources().getDrawable(R.drawable.icon);
            refreshView.setLoadingDrawable(d);
mPullRefreshListView.onRefreshComplete();

        }
    });
```

**Comment by chrisbanes** [comment]
To set just the header drawable call: `setLoadingDrawable(..., Mode.PULL_DOWN_TO_REFRESH);`
To set just the footer drawable call: `setLoadingDrawable(..., Mode.PULL_UP_TO_REFRESH);`

**Comment by pchauhan** [comment]
Thank you Very much.......

**Comment by meablelee2013** [comment]
How to forbid pull up to getmore.Is there has one parameter which i can used in xml to forbid to pull up .

Ths.

**Comment by ckitterl** [comment]
@meablelee2013  Yes, there is a attribute named ptrMode. 

```
        <flag name="disabled" value="0x0" />
        <flag name="pullFromStart" value="0x1" />
        <flag name="pullFromEnd" value="0x2" />
        <flag name="both" value="0x3" />
        <flag name="manualOnly" value="0x4" />
```

**Comment by meablelee2013** [comment]
@ckitterl Thanks ,I get it.But now i have another problem ,I hope i can have a look at the headview(the loading when i pulldown the scrollview or scrolllistview ,when i call the pulltorefreshlistview.oncomplete(),it will dismiss ),that is to say ,i want to simulate the pulldown`s result.
how i can work it.thank you very much.

**Comment by ckitterl** [comment]
I dont think u should use this library. You could look at the source code
which to do pulldown. The key is View's scrollto() function.

On Wed, Oct 16, 2013 at 11:53 AM, meablelee2013 notifications@github.comwrote:

> @ckitterl https://github.com/ckitterl Thanks ,I get it.But now i have
> another problem ,I hope i can have a look at the headview(the loading when
> i pulldown the scrollview or scrolllistview ,when i call the
> pulltorefreshlistview.oncomplete(),it will dismiss ),that is to say ,i want
> to simulate the pulldown`s result.
> how i can work it.thank you very much.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chrisbanes/Android-PullToRefresh/pull/80#issuecomment-26391161
> .

## 

我的名字叫蔡睦堃

**Pull request closed without merging**
