### PR TITLE
Things that I would like to have for my development

### PR DESCRIPTION
**Pull request by hahnjo**
Hi chrisbanes,

these are the changes that I would need for one of my projects.
The first commit makes it easier to use a custom ListView (in my case the SectionListView).
The second one is maybe useful if someone extends one of the PullToRefresh-classes and wants to override these methods. This is currently only possible if the class is in your package.

Greets,
hahnjo

### CODE REVIEW

**Comment by chrisbanes** [comment]
e9fb3d72b3f8f05e6e19ce8803d7806f19e7f2c2: The reason that those methods are package level is so that you can't mess with them. If you want to find out when an event has happened, use `setOnPullEventListener(OnPullEventListener)`.
ff9bc14186fbb762cb76ac147ea38d8dcbbc5d13: I'm not entirely sure _why_ you've done this.

What is the problem with subclassing `PullToRefreshListView`?

**Comment by hahnjo** [comment]
Ok, sorry. I didn't find this listener. It also works with that. So the second commit is rubbish.

I want to have a PullToRefreshListView, but not with the default ListView from android but with the SectionListView from another library. At first, I made a class that merged these two libraries.

```
public class MyPullToRefreshListView extends PullToRefreshAdapterViewBase<SectionListView>
```

But with that there was the issue with scrolling fully to the bottom wasn't possible while the refreshing-view was shown.
I searched and found that it wasn't occuring in the default PullToRefreshListView. So what I would need is

```
public class MyPullToRefreshListView extends PullToRefreshListView<SectionListView>
```

but this isn't possible. That's why I had the idea of a common PullToRefreshListViewBase for your library-PullToRefreshListView and MyPullToRefreshListView.

I hope you understand now what I meant :)

**Comment by chrisbanes** [comment]
You should probably to extend from `PullToRefreshAdapterViewBase`.

What SectionListView implementation are you using? I'll have a look to see how I can make it easier to use ListView-derivative classes.

**Comment by hahnjo** [comment]
As I said, that was what I did at first.
But it wasn't possible to have the implementation that you have in `PullToRefreshListView`. For that I would need to override `onRefreshing`. And these implementations are anyway common for any `ListView`, so why not make a common superclass? This is what I did with the `PullToRefreshListViewBase`.

I'm using this implementation: http://willowtreeapps.github.com/OAK/downloads.html
Pls don't use the current version on their github, I used the binary.

**Comment by chrisbanes** [comment]
I've just committed 424ed33721b44d9b6bcc482b87f1cd4606d33f3a which should fix any problems you have had subclassing. 

It's up to you whether you make your subclass as complicated as `PullToRefreshListView` (with it's extra header/footer Views) or keep it simple like `PullToRefreshGridView`.

**Comment by victory-wu** [comment]
Line 238 : mRefreshableView.addHeaderView(frame, null, false);
Line 317 : addFooterView(mLvFooterLoadingFrame, null, false);

set dividerHeight property 

If I set up a line, you will be upside down will have the line between head and theme

**Pull request closed without merging**
