### PR TITLE
fix for listview dividers not being displayed for rows disabled with isEnabled() adapter method

### PR DESCRIPTION
**Pull request by mplatov**
fixes the bug by wrapping pull to refresh header and footer into FixedViewInfo objects as described in this blog post:
http://blog.uncommons.org/2013/01/24/android-listview-fixing-missingblank-dividers/

This fix resolves the issue for me. All examples in the sample project work fine with this fix applied.

### CODE REVIEW

**Comment by k8s-cloud-io** [comment]
Is there a way to use both top and bottom refresh?
As i have read, this project isnt maintained anymore, can i have a small hint where to implement that piece of code to make it possible? Thanks.

**Comment by mplatov** [comment]
you don't have to implement it, you just need to enable it with configuration option (ptr:ptrMode="both"). Check sample project for examples (e.g.scrollview example).

**Comment by k8s-cloud-io** [comment]
Ok, thanks. Have found all needed things in Code :)

**Comment by chrisbanes** [comment]
This project is deprecated.

**Pull request closed without merging**
