### PR TITLE
Prefix attrs w/ ptr to avoid common res conflicts

### PR DESCRIPTION
**Pull request by brk3**
When compiling a basic project with Android-PullToRefresh and another library that contains attributes such as headerBackground, you get the following error:

[aapt] ./finch/libs/JakeWharton-ActionBarSherlock-df676ad/library/res/values/abs__attrs.xml:222: error: Attribute "headerBackground" has already been defined

This is with ActionBarSherlock 4.0.  According to my research and some advice #android-dev, libraries should prefix custom attributes with a unique namespace.  ActionBarSherlock likely can't do this as it needs to replicate the android-support library as closely as possible.

These small changes mitigate any such problems at least with Android-PullToRefresh.  Have a look and see what you think :)

### CODE REVIEW

**Comment by JakeWharton** [comment]
I wonder if ADT 17 might mitigate this. Is there a bug on b.android.com? Xavier is usually pretty responsive about things like this.

**Comment by chrisbanes** [comment]
I'm not sure on those prefixes. This definitely feels like an Android bug, tag names in different namespaces should be a problem. Either way, I'm planning an update to the styles.xml and attrs for next release so will prefix them in that.

Thanks anyway!

**Comment by chrisbanes** [comment]
I've just tagged v1.2.5 with a prefix for the attrs.

**Comment by brk3** [comment]
Cool thanks for taking the gist of it board. Hopefully it will be addressed somewhere down the line in ADT as Jake said, so we don't have to worry about it.

**Pull request closed without merging**
